### PR TITLE
Update to 44.0

### PR DESCRIPTION
**Pull request by fmuellner**
- Update to 41.rc
- Update to 41.0
- Drop 3.34 support
- Update to 42.beta
- Update to 42.rc
- Update to 42.0
- Update to 44.0

### CODE REVIEW

**Comment by A6GibKm** [comment]
The runtime is now at flathub :100:

**Comment by fmuellner** [comment]
Nice! What was the magic comment to get the bot to re-run the test build again?

**Comment by A6GibKm** [comment]
bot, build

**Comment by A6GibKm** [comment]
But the pr is still using the old runtime

**Comment by fmuellner** [comment]
Mmh, it's meant for flathub-beta. The one for the main repo is in https://github.com/flathub/org.gnome.Extensions/pull/14 (which now passes :tada:)

**Pull request closed without merging**
